<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/MESRS1
spring.datasource.username=postgres
spring.datasource.password=rougha
=======
# Configuration de la datasource PostgreSQL
<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://ep-shiny-thunder-adw4ma1t-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_X9eijdSV4bhk
>>>>>>> 4bd41a85bb56c3d11a6f0f9bb76e2923710d5f64
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/mesrs
spring.datasource.username=mesrs_user
spring.datasource.password=postgres
>>>>>>> oumou

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RAG Service Configuration
rag.service.url=http://127.0.0.1:8000
rag.service.timeout=360
