# Configuration de la datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mesrs
spring.datasource.username=mesrs_user
spring.datasource.password=postgres

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RAG Service Configuration
rag.service.url=http://127.0.0.1:8000
rag.service.timeout=360
