# Configuration de la datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-shiny-thunder-adw4ma1t-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_X9eijdSV4bhk

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
